# Generated by Django 3.1.6 on 2021-02-05 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_time', models.DateTimeField(auto_now=True, verbose_name='Ad time')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('subjects', models.CharField(max_length=1000, verbose_name='Subjects')),
                ('type', models.CharField(max_length=200, verbose_name='Type')),
                ('grade', models.CharField(max_length=200, verbose_name='Class')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('pref_gender', models.CharField(max_length=20, verbose_name='Preferred Gender')),
                ('std_count', models.IntegerField(verbose_name='Student Count')),
                ('time', models.CharField(max_length=200, verbose_name='Teaching Time')),
                ('days', models.IntegerField(verbose_name='How many days a week')),
                ('location', models.CharField(max_length=1000, verbose_name='Location')),
                ('salary', models.IntegerField(verbose_name='Monthly Salary')),
                ('taken', models.BooleanField(default=False, verbose_name='Taken')),
                ('approve', models.BooleanField(default=False)),
                ('timeout', models.DateTimeField(verbose_name='Run This Ad Until')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Question')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Date proposed')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.ad', verbose_name='Ad')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Date Started')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Date finished')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.ad', verbose_name='Ad')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.proposal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.question')),
            ],
        ),
    ]
