# Generated by Django 3.1.6 on 2021-02-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.ad')),
            ],
        ),
    ]
